-- Seed data for testing
--
-- NOTE: Test users CANNOT be created via seed.sql because password hashing
-- must be done by Supabase Auth service, not by SQL.
--
-- To create test users, run after `npx supabase start`:
--   npm run db:init-users
--
-- Or manually via Supabase Studio:
--   http://127.0.0.1:54323 → Authentication → Users → Add user
--
-- Test users:
--   - test@example.com / testpassword123
--   - skip-auth@example.com / testpassword123
--
-- Sample notes are created automatically by the init-test-users.js script.

