sonar.projectKey=EverFreeNote
sonar.sources=core,ui/web,app
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,ui/mobile/**
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.node.maxspace=8096
