sonar.host.url=http://localhost:9000
sonar.token=squ_6f15c54f3202addbd4f7ebd8c43f9041748bd829
sonar.projectKey=EverFreeNote
sonar.sources=core,ui/web,app
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**
