export interface OAuthAdapter {
  /**
   * Starts platform-specific OAuth flow (web redirect or mobile custom tab/deep link).
   * The authUrl is provider OAuth URL generated by Supabase (contains redirect/callback).
   */
  startOAuth(authUrl: string): Promise<void>
}
